var j=0;
var x;
var pontoM=0;
var pontoJ=0;

function mudaImagem(i){
	j=j+i;
	var imgjog=document.getElementById("jogada");
	if(j<=-1 || j>=3){
		if(j<0){
			j=2;
		}
		if(j>2){
			j=0;
		}
	}
	if(j==0) {
        imgjog.src="imagen/pedra.png";
    }
	if(j==1) {
        imgjog.src="imagen/papel.png";
    } 
	if(j==2) {
        imgjog.src="imagen/tesoura.png";
    } 
}

function start(){
	var aux;
	x=Math.floor(Math.random() * 3);
	if(x==0) {
        document.getElementById("jogadamaquina").src="imagen/pedra.png";
	}
	if(x==1) {
        document.getElementById("jogadamaquina").src="imagen/papel.png";
	} 
	if(x==2) {
        document.getElementById("jogadamaquina").src="imagen/tesoura.png";
	}
	if(x!=j){
		if((x==0 && j==1) || (x==1 && j==2) || (x==2 && j==0)){
			pontoJ=pontoJ+1;
			if((pontoJ%10)==1){
				document.getElementById("ju").src="imagen/1.png";
			}
			if((pontoJ%10)==2){
				document.getElementById("ju").src="imagen/2.png";
			}
			if((pontoJ%10)==3){
				document.getElementById("ju").src="imagen/3.png";
			}
			if((pontoJ%10)==4){
				document.getElementById("ju").src="imagen/4.png";
			}
			if((pontoJ%10)==5){
				document.getElementById("ju").src="imagen/5.png";
			}
			if((pontoJ%10)==6){
				document.getElementById("ju").src="imagen/6.png";
			}
			if((pontoJ%10)==7){
				document.getElementById("ju").src="imagen/7.png";
			}
			if((pontoJ%10)==8){
				document.getElementById("ju").src="imagen/8.png";
			}
			if((pontoJ%10)==9){
				document.getElementById("ju").src="imagen/9.png";
			}
			if(pontoJ>9){
				if((pontoJ%100)/10==0){
					document.getElementById("jd").src="imagen/0.png";
				}
				if((pontoJ%100)/10==1){
					document.getElementById("jd").src="imagen/1.png";
				}
				if((pontoJ%100)/10==2){
					document.getElementById("jd").src="imagen/2.png";
				}
				if((pontoJ%100)/10==3){
					document.getElementById("jd").src="imagen/3.png";
				}
				if((pontoJ%100)/10==4){
					document.getElementById("jd").src="imagen/4.png";
				}
				if((pontoJ%100)/10==5){
					document.getElementById("jd").src="imagen/5.png";
				}
				if((pontoJ%100)/10==6){
					document.getElementById("jd").src="imagen/6.png";
				}
				if((pontoJ%100)/10==7){
					document.getElementById("jd").src="imagen/7.png";
				}
				if((pontoJ%100)/10==8){
					document.getElementById("jd").src="imagen/8.png";
				}
				if((pontoJ%100)/10==9){
					document.getElementById("jd").src="imagen/9.png";
				}
				if((pontoJ%10)==0){
					document.getElementById("ju").src="imagen/0.png";
				}
				if((pontoJ%10)==1){
					document.getElementById("ju").src="imagen/1.png";
				}
				if((pontoJ%10)==2){
					document.getElementById("ju").src="imagen/2.png";
				}
				if((pontoJ%10)==3){
					document.getElementById("ju").src="imagen/3.png";
				}
				if((pontoJ%10)==4){
					document.getElementById("ju").src="imagen/4.png";
				}
				if((pontoJ%10)==5){
					document.getElementById("ju").src="imagen/5.png";
				}
				if((pontoJ%10)==6){
					document.getElementById("ju").src="imagen/6.png";
				}
				if((pontoJ%10)==7){
					document.getElementById("ju").src="imagen/7.png";
				}
				if((pontoJ%10)==8){
					document.getElementById("ju").src="imagen/8.png";
				}
				if((pontoJ%10)==9){
					document.getElementById("ju").src="imagen/9.png";
				}
			}
		}else{
			pontoM=pontoM+1;
			if((pontoM%10)==1){
				document.getElementById("mu").src="imagen/1.png";
			}
			if((pontoM%10)==2){
				document.getElementById("mu").src="imagen/2.png";
			}
			if((pontoM%10)==3){
				document.getElementById("mu").src="imagen/3.png";
			}
			if((pontoM%10)==4){
				document.getElementById("mu").src="imagen/4.png";
			}
			if((pontoM%10)==5){
				document.getElementById("mu").src="imagen/5.png";
			}
			if((pontoM%10)==6){
				document.getElementById("mu").src="imagen/6.png";
			}
			if((pontoM%10)==7){
				document.getElementById("mu").src="imagen/7.png";
			}
			if((pontoM%10)==8){
				document.getElementById("mu").src="imagen/8.png";
			}
			if((pontoM%10)==9){
				document.getElementById("mu").src="imagen/9.png";
			}
			if(pontoM>9){
				if((pontoM%100)/10==0){
					document.getElementById("md").src="imagen/0.png";
				}
				if((pontoM%100)/10==1){
					document.getElementById("md").src="imagen/1.png";
				}
				if((pontoM%100)/10==2){
					document.getElementById("md").src="imagen/2.png";
				}
				if((pontoM%100)/10==3){
					document.getElementById("md").src="imagen/3.png";
				}
				if((pontoM%100)/10==4){
					document.getElementById("md").src="imagen/4.png";
				}
				if((pontoM%100)/10==5){
					document.getElementById("md").src="imagen/5.png";
				}
				if((pontoM%100)/10==6){
					document.getElementById("md").src="imagen/6.png";
				}
				if((pontoM%100)/10==7){
					document.getElementById("md").src="imagen/7.png";
				}
				if((pontoM%100)/10==8){
					document.getElementById("md").src="imagen/8.png";
				}
				if((pontoM%100)/10==9){
					document.getElementById("md").src="imagen/9.png";
				}
				if(pontoM%10==0){
					document.getElementById("mu").src="imagen/0.png";
				}
				if(pontoM%10==1){
					document.getElementById("mu").src="imagen/1.png";
				}
				if(pontoM%10==2){
					document.getElementById("mu").src="imagen/2.png";
				}
				if(pontoM%10==3){
					document.getElementById("mu").src="imagen/3.png";
				}
				if(pontoM%10==4){
					document.getElementById("mu").src="imagen/4.png";
				}
				if(pontoM%10==5){
					document.getElementById("mu").src="imagen/5.png";
				}
				if(pontoM%10==6){
					document.getElementById("mu").src="imagen/6.png";
				}
				if(pontoM%10==7){
					document.getElementById("mu").src="imagen/7.png";
				}
				if(pontoM%10==8){
					document.getElementById("mu").src="imagen/8.png";
				}
				if(pontoM%10==9){
					document.getElementById("mu").src="imagen/9.png";
				}
			}
		}
	}else{
		//alert("Empate");
	}
}

	

